org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Sprint 7 (2026-05-07): tắt incremental Kotlin compile để tránh
# "Storage already registered" + "this and base files have different roots"
# (do source plugin trên C: và build cache trên E: khác drive).
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
